DELETE FROM t_a001 T WHERE EXISTS ( SELECT * FROM  J1 WHERE EXISTS ( SELECT * FROM  J2 WHERE J2. = J1. AND J1.DELETE_ID = delete_id  ) AND J1 = T.) WHERE o_c
;
DELETE FROM t_a010 T WHERE EXISTS ( SELECT * FROM  J1 WHERE EXISTS ( SELECT * FROM  J2 WHERE J2. = J1. AND J1.DELETE_ID = delete_id  ) AND J1 = T.);
DELETE FROM t_a003 T WHERE EXISTS ( SELECT * FROM t_j1 J1 WHERE J1c_j1 = T.c_t1 AND J1.DELETE_ID = delete_id ) WHERE o_c
;
DELETE FROM t_a004 T WHERE EXISTS ( SELECT * FROM t_j1 J1 WHERE J1c_j1 = T. AND J1.DELETE_ID = delete_id ) WHERE o_c
;
DELETE FROM t_a006 T WHERE EXISTS ( SELECT * FROM t_j1 J1 WHERE J1c_j1 = T.c_t1 AND J1.DELETE_ID = delete_id ) WHERE o_c
;
DELETE FROM t_a007 T WHERE EXISTS ( SELECT * FROM t_j1 J1 WHERE J1 = T. AND J1.DELETE_ID = delete_id ) WHERE o_c
;
DELETE FROM t_a009 T WHERE EXISTS ( SELECT * FROM t_j1 J1 WHERE J1c_j1 = T.c_t1 AND J1.DELETE_ID = delete_id ) WHERE o_c
;
DELETE FROM t_a001 T WHERE T.DELETE_ID = delete_id AND o_c
;
DELETE FROM t_a010 T WHERE T.DELETE_ID = delete_id;
